---
upstream_aggregated_ethernet_interfaces:
  - name: ae1
    members:
      - ge-0/0/40
      - ge-1/0/40
  - name: ae2
    members:
      - ge-0/0/41
      - ge-1/0/41
qfx_chassis:
  - serial: DC753-C
    member: 0
  - serial: X4085-C
    member: 1
virtual_routers:
  - dmz-untrusted
  - lan-trusted
lan_interfaces:
# UniFi switch (temporary)
  - name: ge-0/0/36
    vlans:
      - 1
      - 100
      - 103
      - 350
      - 500
    virtual_router: lan-trusted
    rstp: true
    native_vlan_id: 1
    vlan_mode: trunk
# Hypervisors
  # node1
  - name: ae3
    lacp_mon: fast
    lacp_mode: active
    vlans:
      - 100
      - 102
      - 103
      - 300
      - 350
    virtual_router: lan-trusted
    native_vlan_id: 300
    members:
      - ge-0/0/6
      - ge-0/0/7
      - ge-0/0/8
      - ge-0/0/9
    vlan_mode: trunk
  # node2
  - name: ae4
    lacp_mon: fast
    lacp_mode: active
    vlans:
      - 100
      - 102
      - 103
      - 300
      - 350
    virtual_router: lan-trusted
    native_vlan_id: 300
    members:
      - ge-0/0/10
      - ge-0/0/11
      - ge-0/0/12
      - ge-0/0/13
    vlan_mode: trunk
  # node3
  - name: ae5
    lacp_mon: fast
    lacp_mode: active
    vlans:
      - 100
      - 102
      - 103
      - 300
      - 350
    virtual_router: lan-trusted
    native_vlan_id: 300
    members:
      - ge-0/0/14
      - ge-0/0/15
      - ge-0/0/16
      - ge-0/0/17
    vlan_mode: trunk
  # node4 - UNUSED!!
  - name: ae6
    native_vlan_id: 300
    vlans:
      - 100
      - 102
      - 103
      - 300
      - 350
    virtual_router: lan-trusted
    members:
      - ge-0/0/18
      - ge-0/0/19
    vlan_mode: trunk
# NAS
  - name: ae7
    vlans:
      - 1
      - 100
      - 102
    virtual_router: lan-trusted
    native_vlan_id: 1
    members:
      - ge-0/0/20
      - ge-0/0/21
      - ge-0/0/22
      - ge-0/0/23
    vlan_mode: trunk
# Laptop
  - name: ge-0/0/24
    native_vlan_id: 300
    vlans:
      - 100
      - 102
      - 300
      - 316
    virtual_router: lan-trusted
    vlan_mode: trunk
# Cisco switch in media rack
  - name: ae8
    vlans:
      - 1
      - 100
      - 102
      - 103
      - 300
      - 350
    virtual_router: lan-trusted
    rstp: true
    native_vlan_id: 1
    vlan_mode: trunk
    members:
      - ge-0/0/38
      - ge-0/0/39
# Dell XR4000 Sled1
  - name: ae9
    vlans:
      - 1
      - 102
    virtual_router: lan-trusted
    rstp: true
    native_vlan_id: 1
    vlan_mode: trunk
    members:
      - ge-0/0/26
      - ge-0/0/27
# Dell XR4000 Sled2
  - name: ae10
    vlans:
      - 1
      - 102
    virtual_router: lan-trusted
    rstp: true
    native_vlan_id: 1
    vlan_mode: trunk
    members:
      - ge-0/0/30
      - ge-0/0/31


