---
aggregated_ethernet_interfaces:
  - name: ae1
    members:
      - ge-0/0/40
      - ge-1/0/40
  - name: ae2
    members:
      - ge-0/0/41
      - ge-1/0/41
qfx_chassis:
  - serial: DC753-C
    member: 0
  - serial: P8056-C
    member: 1
virtual_routers:
  - dmz-untrusted
  - lan-trusted
lan_interfaces:
# Cisco switch in media rack
  - name: ge-0/0/38
    vlans:
      - 1
      - 100
      - 103
    virtual_router: lan-trusted
    rstp: true
    native_vlan_id: 1
# UniFi switch (temporary)
  - name: ge-1/0/38
    vlans:
      - 1
      - 100
      - 102
      - 103
      - 300
      - 350
    virtual_router: lan-trusted
    rstp: true
    native_vlan_id: 1
# Hypervisors
  # node1
  - name: ge-0/0/6
    vlans:
      - 1
      - 300
    virtual_router: lan-trusted
    native_vlan_id: 1
  - name: ae3
    vlans:
      - 1
      - 100
      - 102
      - 103
      - 350
    virtual_router: lan-trusted
    native_vlan_id: 1
    members:
      - ge-1/0/6
      - ge-0/0/8
      - ge-1/0/8
  # node2
  - name: ge-0/0/10
    vlans:
      - 1
      - 300
    virtual_router: lan-trusted
    native_vlan_id: 1
  - name: ae4
    vlans:
      - 1
      - 100
      - 102
      - 103
      - 350
    virtual_router: lan-trusted
    native_vlan_id: 1
    members:
      - ge-1/0/10
      - ge-0/0/12
      - ge-0/0/12
  # node3
  - name: ge-0/0/14
    vlans:
      - 1
      - 300
    virtual_router: lan-trusted
    native_vlan_id: 1
  - name: ae5
    vlans:
      - 1
      - 100
      - 102
      - 103
      - 350
    virtual_router: lan-trusted
    native_vlan_id: 1
    members:
      - ge-1/0/14
      - ge-0/0/16
      - ge-1/0/16
  # node4
  - name: ae6
    vlans:
      - 1
      - 100
      - 102
      - 103
      - 300
      - 350
    virtual_router: lan-trusted
    native_vlan_id: 1
    members:
      - ge-0/0/18
      - ge-1/0/18
# NAS
  - name: ae7
    vlans:
      - 1
      - 100
      - 102
    virtual_router: lan-trusted
    native_vlan_id: 1
    members:
      - ge-0/0/20
      - ge-1/0/20
      - ge-0/0/22
      - ge-1/0/22


