aggregated_ethernet_interfaces:
  - name: ae1
    members:
      - ge-0/0/40
      - ge-1/0/40
  - name: ae2
    members:
      - ge-0/0/41
      - ge-1/0/41
qfx_chassis:
  - serial: DC753-C
    member: 0
  - serial: P8056-C
    member: 1
