---
system_name_servers:
  - 1.1.1.1
pppoe_physical_interface: pt-1/0/0
pppoe_username: alexander.hussey@internode.on.net
webinterface_vlan: 100
security_zones:
  - name: lan-trust
    allowed_protocols:
      - all
dhcp_wan1:
  - if: ge-0/0/2
    nh: 192.168.3.1
  - if: ge-3/0/2
    nh: 192.168.3.1
dhcp_wan2:
  - if: ge-0/0/3
    nh: 192.168.2.1
  - if: ge-3/0/3
    nh: 192.168.2.1
physical_interfaces:
  - name: lan1
    if: ge-0/0/4
  - name: lan2
    if: ge-0/0/5
  - name: lan3
    if: ge-3/0/4
  - name: lan4
    if: ge-3/0/5
subnets:
# Services
  - cidr: 192.168.100.1/24
    dhcp_start: 192.168.100.10
    dhcp_end: 192.168.100.254
    domain_name: hussdogg.com
    name_servers:
      - 192.168.100.25
      - 192.168.100.3
      - 192.168.100.24
    gateway: 192.168.100.1
    lease_time: 3600
    name: services
    vlan:
      tag: services
      id: 100
      l3_interface: irb.100
# Security
  - cidr: 192.168.101.1/24
    dhcp_start: 192.168.101.10
    dhcp_end: 192.168.101.254
    domain_name: hussdogg.com
    name_servers:
      - 192.168.100.25
      - 192.168.100.3
      - 192.168.100.24
    gateway: 192.168.101.1
    lease_time: 3600
    name: security
    vlan:
      tag: security
      id: 101
      l3_interface: irb.101
# DMZ
  - cidr: 192.168.102.1/24
    dhcp_start: 192.168.102.10
    dhcp_end: 192.168.102.254
    domain_name: hussdogg.com
    name_servers:
      - 192.168.100.25
      - 192.168.100.3
      - 192.168.100.24
    gateway: 192.168.102.1
    lease_time: 3600
    name: dmz
    vlan:
      tag: dmz
      id: 102
      l3_interface: irb.102
# Clients
  - cidr: 192.168.103.1/24
    dhcp_start: 192.168.103.10
    dhcp_end: 192.168.103.254
    domain_name: hussdogg.com
    name_servers:
      - 192.168.100.25
      - 192.168.100.3
      - 192.168.100.24
    gateway: 192.168.103.1
    lease_time: 3600
    name: clients
    vlan:
      tag: clients
      id: 103
      l3_interface: irb.103
# VMs
  - cidr: 10.10.0.1/16
    dhcp_start: 10.10.0.10
    dhcp_end: 10.10.255.254
    domain_name: hussdogg.com
    name_servers:
      - 192.168.100.25
      - 192.168.100.3
      - 192.168.100.24
    gateway: 10.10.0.1
    lease_time: 3600
    name: vms
    vlan:
      tag: vms
      id: 300
      l3_interface: irb.300
# Hypervisors
  - cidr: 172.18.0.1/16
    dhcp_start: 172.18.0.10
    dhcp_end: 172.18.255.254
    domain_name: hussdogg.com
    name_servers:
      - 192.168.100.25
      - 192.168.100.3
      - 192.168.100.24
    gateway: 172.18.0.1
    lease_time: 3600
    name: hypervisors
    vlan:
      tag: hypervisors
      id: 350
      l3_interface: irb.350
