---
#pppoe_physical_interface: pt-1/0/0
pppoe_username: alexander.hussey@internode.on.net
webinterface: reth1.100
security_zones:
  - name: lan-trust
    allowed_protocols:
      - all
dhcp_wan1_nh: 192.168.3.1
dhcp_wan1:
  - ge-0/0/2
  - ge-3/0/2
dhcp_wan2_nh: 192.168.2.1
dhcp_wan2:
  - ge-0/0/3
  - ge-3/0/3
physical_interfaces:
  - if: ge-0/0/4
  - if: ge-0/0/5
  - if: ge-3/0/4
  - if: ge-3/0/5