---
#pppoe_physical_interface: pt-1/0/0
#pppoe_username: alexander.hussey@internode.on.net
webinterface: reth0.100
dhcp_wan1_nh: 192.168.3.1
dhcp_wan1:
  - ge-0/0/2
  - ge-3/0/2
dhcp_wan2_nh: 192.168.2.1
dhcp_wan2:
  - ge-0/0/3
  - ge-3/0/3
physical_interfaces:
  - if: ge-0/0/4
  - if: ge-0/0/5
  - if: ge-3/0/4
  - if: ge-3/0/5
fabric_interfaces:
  - interface: ge-0/0/7
    fab_number: 0
  - interface: ge-3/0/7
    fab_number: 1
security_zones:
  - name: lan-trusted
    allowed_protocols:
      - all
wan_virtual_routers:
  - primary-isp-1-untrusted
  - primary-isp-2-untrusted
  - alternate-isp-1-untrusted
  - alternate-isp-2-untrusted
virtual_routers:
  - lan-trusted
dhcp_reservations:
  - name: services
    hosts:
      - mac: 02:98:c5:36:39:7b
        ip: 192.168.100.230
        name: hussws03
        subnet_name: services
