---
- name: Install and configure conserver
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
   - name: Install the conserver application
     ansible.builtin.dnf:
       name:
        - conserver
        - conserver-client
       state: latest
   - name: Configure conserver application
     ansible.builtin.template:
       src: templates/conserver.cf
       dest: /etc/conserver.cf
   - name: Configure conserver connections
     ansible.builtin.copy:
       src: files/conserver.passwd
       dest: /etc/conserver.passwd
   - name: Configure conserver client console
     ansible.builtin.copy:
       src: files/console.cf
       dest: /etc/console.cf
   - name: Configure conserver systemd service
     ansible.builtin.copy:
       src: files/conserver.service
       dest: /etc/systemd/system/conserver.service
   - name: Ensure conserver service is enable and running
     ansible.builtin.systemd_service:
       name: conserver.service
       enabled: true
       state: started
       daemon_reload: true
        
